/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package neu.oncampusams.campusadministration.CampusAdmin;

import com.mysql.cj.jdbc.result.ResultSetMetaData;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import neu.oncampusams.databaseConnection.JDBCConnection;
import neu.oncampusams.systemadministration.SystemAdmin.Login;

/**
 *
 * @author Yamini Manral
 */
public class CampusAdmin extends javax.swing.JFrame {

    String emailID= "ds.d@northeastern.edu"; //declare the variable that will hold the email id

    /**
     * Creates new form test
     */
    public CampusAdmin() {
        initComponents();
        updateAutoPupulate(emailID);
    }

    public CampusAdmin(String eid) {
        initComponents();
        emailID = eid; //passing the value of emailid
    }
    CampusAdminInfoDirectory campusAdminInfoDirectory = new CampusAdminInfoDirectory();
    CampusAdminInfo campusAdminInfo = new CampusAdminInfo();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        lblPrsnlEmail3 = new javax.swing.JLabel();
        lblPhone3 = new javax.swing.JLabel();
        lblNewPass7 = new javax.swing.JLabel();
        lblNewPass8 = new javax.swing.JLabel();
        canteenName = new javax.swing.JTextField();
        CanteenAdmin = new javax.swing.JTextField();
        Location1 = new javax.swing.JTextField();
        Contact1 = new javax.swing.JTextField();
        addDetails1 = new javax.swing.JButton();
        bg1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        bg2 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable5 = new javax.swing.JTable();
        searchField = new javax.swing.JTextField();
        lblEmailId2 = new javax.swing.JLabel();
        lblPrsnlEmail2 = new javax.swing.JLabel();
        lblPhone2 = new javax.swing.JLabel();
        lblNewPass4 = new javax.swing.JLabel();
        lblNewPass5 = new javax.swing.JLabel();
        oneBhk = new javax.swing.JTextField();
        twoBhk = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Shared = new javax.swing.JTextField();
        stuRes = new javax.swing.JTextField();
        lblNewPass6 = new javax.swing.JLabel();
        bCampus = new javax.swing.JTextField();
        addDetails2 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        bg3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        lblEmailId = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        updatePhone = new javax.swing.JTextField();
        updateMailAdmin = new javax.swing.JButton();
        pwdPass1 = new javax.swing.JPasswordField();
        lblNewPass1 = new javax.swing.JLabel();
        updateEmail = new javax.swing.JTextField();
        pwdPass = new javax.swing.JTextField();
        bg4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        addDetails = new javax.swing.JButton();
        lblPrsnlEmail1 = new javax.swing.JLabel();
        lblPhone1 = new javax.swing.JLabel();
        lblNewPass2 = new javax.swing.JLabel();
        lblNewPass3 = new javax.swing.JLabel();
        gymName = new javax.swing.JTextField();
        gymAdmin = new javax.swing.JTextField();
        Location = new javax.swing.JTextField();
        Contact = new javax.swing.JTextField();
        bg5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Campus Administrator Portal");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1400, 700));
        setMinimumSize(new java.awt.Dimension(1400, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1600, 1000));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1600, 1000));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1600, 1000));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Canteen ID", "Canteen Name", "Location", "Contact", "Canteen Admin"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel9.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 690, 110));

        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton6.setText("Refresh");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 440, 120, 40));

        lblPrsnlEmail3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrsnlEmail3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrsnlEmail3.setText("Canteen Name");
        jPanel9.add(lblPrsnlEmail3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 140, 30));

        lblPhone3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPhone3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone3.setText("Location");
        jPanel9.add(lblPhone3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, 140, 30));

        lblNewPass7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass7.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass7.setText("Contact");
        jPanel9.add(lblNewPass7, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 140, 30));

        lblNewPass8.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass8.setText("Canteen Admin");
        jPanel9.add(lblNewPass8, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, 180, 30));

        canteenName.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        canteenName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                canteenNameActionPerformed(evt);
            }
        });
        jPanel9.add(canteenName, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 50, 230, 30));

        CanteenAdmin.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        CanteenAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CanteenAdminActionPerformed(evt);
            }
        });
        jPanel9.add(CanteenAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 200, 230, 30));

        Location1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Location1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Location1ActionPerformed(evt);
            }
        });
        jPanel9.add(Location1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, 230, 30));

        Contact1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Contact1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Contact1ActionPerformed(evt);
            }
        });
        jPanel9.add(Contact1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, 230, 30));

        addDetails1.setBackground(new java.awt.Color(255, 0, 0));
        addDetails1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDetails1.setForeground(new java.awt.Color(255, 255, 255));
        addDetails1.setText("Add details");
        addDetails1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDetails1ActionPerformed(evt);
            }
        });
        jPanel9.add(addDetails1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 130, 40));

        jPanel3.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 770, 520));

        bg1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/canteen_bg.jpg"))); // NOI18N
        jPanel3.add(bg1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        jTabbedPane1.addTab("Canteen Details", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/canteen .png")), jPanel3); // NOI18N

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "AccoAdmin ID", "Name", "Contact", "Building Assigned"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel7.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 490, 160));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Details of Accommodation Admins");
        jPanel7.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 490, 40));

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("View Admins");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel7.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, 40));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, 580, 450));

        bg2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/admin_bg.jpg"))); // NOI18N
        jPanel4.add(bg2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        jTabbedPane1.addTab("Accomodation Admin", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/admin.png")), jPanel4); // NOI18N

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jTable5.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Building ID", "Building Name", "Availability", "Warden Assigned", "Students Residing"
            }
        ));
        jScrollPane5.setViewportView(jTable5);

        jPanel10.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 680, 110));

        searchField.setForeground(new java.awt.Color(153, 153, 153));
        searchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        searchField.setText("Search");
        searchField.setToolTipText("");
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        jPanel10.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 230, 40));

        lblEmailId2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmailId2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailId2.setText("1BHK Available");
        jPanel10.add(lblEmailId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 150, 30));

        lblPrsnlEmail2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrsnlEmail2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrsnlEmail2.setText("2BHK Available");
        jPanel10.add(lblPrsnlEmail2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, 150, 30));

        lblPhone2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPhone2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone2.setText("Shared Available");
        jPanel10.add(lblPhone2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 150, 30));

        lblNewPass4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass4.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass4.setText("Student residing");
        jPanel10.add(lblNewPass4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 150, 30));

        lblNewPass5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass5.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass5.setText("Building name");
        jPanel10.add(lblNewPass5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, 30));

        oneBhk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        oneBhk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBhkActionPerformed(evt);
            }
        });
        jPanel10.add(oneBhk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 230, 30));

        twoBhk.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        twoBhk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBhkActionPerformed(evt);
            }
        });
        jPanel10.add(twoBhk, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 180, 230, 30));

        Name.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        jPanel10.add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 30, 230, 30));

        Shared.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Shared.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SharedActionPerformed(evt);
            }
        });
        jPanel10.add(Shared, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 230, 230, 30));

        stuRes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        stuRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stuResActionPerformed(evt);
            }
        });
        jPanel10.add(stuRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 280, 230, 30));

        lblNewPass6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass6.setText("Building campus");
        jPanel10.add(lblNewPass6, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 190, 30));

        bCampus.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        bCampus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCampusActionPerformed(evt);
            }
        });
        jPanel10.add(bCampus, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 80, 230, 30));

        addDetails2.setBackground(new java.awt.Color(255, 0, 0));
        addDetails2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDetails2.setForeground(new java.awt.Color(255, 255, 255));
        addDetails2.setText("Add building");
        addDetails2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDetails2ActionPerformed(evt);
            }
        });
        jPanel10.add(addDetails2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 140, 40));

        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jButton7.setText("Refresh");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel10.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 510, 120, 40));

        jPanel6.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 730, 580));

        bg3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/building_bg.jpg"))); // NOI18N
        jPanel6.add(bg3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        jTabbedPane1.addTab("Building Details", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/office-building.png")), jPanel6); // NOI18N

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailId.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmailId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailId.setText("Email Id");
        jPanel11.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 40));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Phone Number");
        jPanel11.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 150, 40));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword.setText("Password");
        jPanel11.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 160, 40));

        updatePhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        updatePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhoneActionPerformed(evt);
            }
        });
        jPanel11.add(updatePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 200, 40));

        updateMailAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateMailAdmin.setText("Update");
        updateMailAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMailAdminActionPerformed(evt);
            }
        });
        jPanel11.add(updateMailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 120, 50));

        pwdPass1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel11.add(pwdPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 200, 200, 40));

        lblNewPass1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass1.setText("Re-Enter New Password");
        jPanel11.add(lblNewPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 190, 40));

        updateEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        updateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmailActionPerformed(evt);
            }
        });
        jPanel11.add(updateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 200, 40));

        pwdPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pwdPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPassActionPerformed(evt);
            }
        });
        jPanel11.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 200, 40));

        jPanel8.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 490, 360));

        bg4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/profile_bg.jpg"))); // NOI18N
        jPanel8.add(bg4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        jTabbedPane1.addTab("Profile", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/updated.png")), jPanel8); // NOI18N

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Gym ID", "Gym Name", "Location", "Contact", "Gym Admin"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        jTable1.getAccessibleContext().setAccessibleDescription("");

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, 520, 170));

        jButton5.setText("Refresh");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 490, 120, 40));

        addDetails.setBackground(new java.awt.Color(255, 0, 0));
        addDetails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addDetails.setForeground(new java.awt.Color(255, 255, 255));
        addDetails.setText("Add details");
        addDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addDetailsActionPerformed(evt);
            }
        });
        jPanel5.add(addDetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 130, 40));

        lblPrsnlEmail1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPrsnlEmail1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrsnlEmail1.setText("Gym Name");
        jPanel5.add(lblPrsnlEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 140, 30));

        lblPhone1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPhone1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone1.setText("Location");
        jPanel5.add(lblPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 30));

        lblNewPass2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass2.setText("Contact");
        jPanel5.add(lblNewPass2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 140, 30));

        lblNewPass3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass3.setText("Gym Admin");
        jPanel5.add(lblNewPass3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 180, 30));

        gymName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gymName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymNameActionPerformed(evt);
            }
        });
        jPanel5.add(gymName, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 230, 30));

        gymAdmin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gymAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gymAdminActionPerformed(evt);
            }
        });
        jPanel5.add(gymAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 230, 30));

        Location.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Location.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LocationActionPerformed(evt);
            }
        });
        jPanel5.add(Location, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, 230, 30));

        Contact.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Contact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactActionPerformed(evt);
            }
        });
        jPanel5.add(Contact, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, 230, 30));

        jPanel2.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 20, 590, 560));

        bg5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/gym_bg.jpg"))); // NOI18N
        jPanel2.add(bg5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        jTabbedPane1.addTab("Gym Details", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/dumbbell (1).png")), jPanel2); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1090, 700));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Northeastern University");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("On-Campus Accommodation");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/neulogo1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 170, 150));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("*email*");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 270, 40));

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, 90, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Management System");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        String id;
        String name;
        String email;
        model.setRowCount(0);
        try {
            Connection connection = JDBCConnection.Connect();
            Statement statement = connection.createStatement();

            ResultSet rs = statement.executeQuery("select accomodationadmintable.accoAdminId, CONCAT(accomodationadmintable.fName, ' ' , accomodationadmintable.lName) "
                    + ", accomodationadmintable.campus from oncampusamsdb.campusadmintable, oncampusamsdb.accomodationadmintable"
                    + " WHERE campusadmintable.campus = accomodationadmintable.campus;");

            //push column values to the table fields
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            while (rs.next()) {
                id = rs.getString(1);
                name = rs.getString(2);
                email = rs.getString(3);
                String[] row = {id, name, email};
                model.addRow(row);
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        
        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna logout?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        String gymid;
        String name;
        String location;
        String contact;
        String gym_admin;
        model.setRowCount(0);
        try {
            Connection connection = JDBCConnection.Connect();
            Statement statement = connection.createStatement();

            ResultSet rs = statement.executeQuery("select gym.gymid, gym.name, gym.location, gym.contact, gym.gym_admin from oncampusamsdb.campusadmintable, oncampusamsdb.gym "
                    + "WHERE campusadmintable.campus = gym.location;");

            //push column values to the table fields
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            while (rs.next()) {
                gymid = rs.getString(1);
                name = rs.getString(2);
                location = rs.getString(3);
                contact = rs.getString(4);
                gym_admin = rs.getString(5);
                String[] row = {gymid, name, location, contact, gym_admin};
                model.addRow(row);
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }

    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed

        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        String id;
        String name;
        String location;
        String contact;
        String canteen_admin;
        model.setRowCount(0);
        try {
            Connection connection = JDBCConnection.Connect();
            Statement statement = connection.createStatement();

            ResultSet rs = statement.executeQuery("select canteen.id, canteen.name, canteen.location, canteen.contact, canteen.canteen_admin from oncampusamsdb.campusadmintable, oncampusamsdb.canteen WHERE campusadmintable.campus = canteen.location;");

            //push column values to the table fields
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            while (rs.next()) {
                id = rs.getString(1);
                name = rs.getString(2);
                location = rs.getString(3);
                contact = rs.getString(4);
                canteen_admin = rs.getString(5);
                String[] row = {id, name, location, contact, canteen_admin};
                model.addRow(row);
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void addDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetailsActionPerformed

//        String gymid = gymId.getText();
        String name = gymName.getText();
        String location = Location.getText();
        String contact = Contact.getText();
        String gym_admin = gymAdmin.getText();

        CampusAdminInfo gym = new CampusAdminInfo();
//                gym.setGym_id(gymid);
        gym.setGym_name(name);
        gym.setGym_location(location);
        gym.setGym_contact(contact);
        gym.setGym_admin(gym_admin);

        campusAdminInfoDirectory.addGym(gym); //calling using object of CAI Directory
        JOptionPane.showMessageDialog(this, "Gym added successfully");
//                gymId.setText("");
        gymName.setText("");
        Location.setText("");
        Contact.setText("");
        gymAdmin.setText("");

    }//GEN-LAST:event_addDetailsActionPerformed

    private void gymNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gymNameActionPerformed

    private void gymAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gymAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gymAdminActionPerformed

    private void LocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LocationActionPerformed

    private void ContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactActionPerformed

    private void oneBhkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBhkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_oneBhkActionPerformed

    private void twoBhkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBhkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_twoBhkActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void SharedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SharedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SharedActionPerformed

    private void stuResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stuResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stuResActionPerformed

    private void bCampusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCampusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bCampusActionPerformed

    private void canteenNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_canteenNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_canteenNameActionPerformed

    private void CanteenAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CanteenAdminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CanteenAdminActionPerformed

    private void Location1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Location1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Location1ActionPerformed

    private void Contact1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Contact1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Contact1ActionPerformed

    private void addDetails1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetails1ActionPerformed

        String name = canteenName.getText();
        String location = Location1.getText();
        String contact = Contact1.getText();
        String canteen_admin = CanteenAdmin.getText();

        CampusAdminInfo canteen = new CampusAdminInfo();
//                gym.setGym_id(gymid);
        canteen.setCanteen_name(name);
        canteen.setCanteen_location(location);
        canteen.setCanteen_contact(contact);
        canteen.setCanteen_admin(canteen_admin);

        campusAdminInfoDirectory.addCanteen(canteen); //calling using object of CAI Directory
        JOptionPane.showMessageDialog(this, "Canteen added successfully");
//                gymId.setText("");
        canteenName.setText("");
        Location1.setText("");
        Contact1.setText("");
        CanteenAdmin.setText("");

    }//GEN-LAST:event_addDetails1ActionPerformed

    private void addDetails2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addDetails2ActionPerformed
        //for new building addition
        String name = Name.getText();
        String campus = bCampus.getText();
        String onebhk = oneBhk.getText();
        String twobhk = twoBhk.getText();
        String shared = Shared.getText();
        String residing = stuRes.getText();

        CampusAdminInfo building = new CampusAdminInfo();

        building.setBuilding_name(name);
        building.setCampus(campus);
        building.setOnebhk(onebhk);
        building.setTwobhk(twobhk);
        building.setShared(shared);
        building.setResiding(residing);

        campusAdminInfoDirectory.addBuilding(building); //calling using object of CAI Directory
        JOptionPane.showMessageDialog(this, "Building created successfully");
//                gymId.setText("");
        Name.setText("");
        bCampus.setText("");
        oneBhk.setText("");
        twoBhk.setText("");
        Shared.setText("");
        stuRes.setText("");

    }//GEN-LAST:event_addDetails2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        String bID;
        String name;
        String avail;
        String warden;
        String stuRes;
        model.setRowCount(0);
        try {
            Connection connection = JDBCConnection.Connect();
            Statement statement = connection.createStatement();

            ResultSet rs = statement.executeQuery("select buildingtable.buildingId, buildingtable.buildingName, buildingtable.1BhkAvail+buildingtable.2BhkAvail+buildingtable.sharedAvail,"
                    + " buildingtable.wardenAssigned, buildingtable.studentResiding from oncampusamsdb.campusadmintable, oncampusamsdb.buildingtable"
                    + " WHERE campusadmintable.campus = buildingtable.campus;");

//            statement.execute( "UPDATE `oncampusamsdb`.`buildingtable` SET `totalAvail` = 1BhkAvail+2BhkAvail+sharedAvail where buildingId =  '" + bID + "'");
            //push column values to the table fields
            ResultSetMetaData rsmd = (ResultSetMetaData) rs.getMetaData();
            while (rs.next()) {
                bID = rs.getString(1);
                name = rs.getString(2);
                avail = rs.getString(3);
                warden = rs.getString(4);
                stuRes = rs.getString(5);
                String[] row = {bID, name, avail, warden, stuRes};
                model.addRow(row);
            }
            connection.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }


    }//GEN-LAST:event_jButton7ActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed

    }//GEN-LAST:event_searchFieldActionPerformed

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased

        String query1 = searchField.getText();
        filterSearch(query1);

    }//GEN-LAST:event_searchFieldKeyReleased

    private void updatePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePhoneActionPerformed

    private void updateMailAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMailAdminActionPerformed
        // TODO add your handling code here:
        if (!(pwdPass.getText()).equals(pwdPass1.getText())) {
            JOptionPane.showMessageDialog(this, "Passwords doesn't match, please try again!");
            pwdPass.setText("");
            pwdPass1.setText("");
            return;
        }
        CampusAdminInfo campusAdminInfo = new CampusAdminInfo();
        campusAdminInfo.setPhone(updatePhone.getText());
        campusAdminInfo.setEmailID(emailID);
        campusAdminInfo.setPassword(pwdPass1.getText());
        campusAdminInfoDirectory.updateCampusAdminDetails(campusAdminInfo);
        updateAutoPupulate(emailID);
        pwdPass.setText("");
        pwdPass1.setText("");
        updatePhone.setText("");
        JOptionPane.showMessageDialog(this, "Details updated successfully!");

    }//GEN-LAST:event_updateMailAdminActionPerformed

    private void updateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmailActionPerformed

    private void pwdPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CampusAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CampusAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CampusAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CampusAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CampusAdmin().setVisible(true);
            }
        });
    }

    private void filterSearch(String query) {
        DefaultTableModel model = (DefaultTableModel) jTable5.getModel();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);
        jTable5.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(query));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CanteenAdmin;
    private javax.swing.JTextField Contact;
    private javax.swing.JTextField Contact1;
    private javax.swing.JTextField Location;
    private javax.swing.JTextField Location1;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Shared;
    private javax.swing.JButton addDetails;
    private javax.swing.JButton addDetails1;
    private javax.swing.JButton addDetails2;
    private javax.swing.JTextField bCampus;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bg5;
    private javax.swing.JTextField canteenName;
    private javax.swing.JTextField gymAdmin;
    private javax.swing.JTextField gymName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable5;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblEmailId2;
    private javax.swing.JLabel lblNewPass1;
    private javax.swing.JLabel lblNewPass2;
    private javax.swing.JLabel lblNewPass3;
    private javax.swing.JLabel lblNewPass4;
    private javax.swing.JLabel lblNewPass5;
    private javax.swing.JLabel lblNewPass6;
    private javax.swing.JLabel lblNewPass7;
    private javax.swing.JLabel lblNewPass8;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone1;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblPhone3;
    private javax.swing.JLabel lblPrsnlEmail1;
    private javax.swing.JLabel lblPrsnlEmail2;
    private javax.swing.JLabel lblPrsnlEmail3;
    private javax.swing.JButton logout;
    private javax.swing.JTextField oneBhk;
    private javax.swing.JTextField pwdPass;
    private javax.swing.JPasswordField pwdPass1;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField stuRes;
    private javax.swing.JTextField twoBhk;
    private javax.swing.JTextField updateEmail;
    private javax.swing.JButton updateMailAdmin;
    private javax.swing.JTextField updatePhone;
    // End of variables declaration//GEN-END:variables

    public void SetEmailID() {
        lblEmail.setText(emailID);
    }
//    
//    private boolean FormValidation(){
//    boolean validation = true;
//    if(!txtPhone1.getText().matches("^[0-9]{10}$") || txtPhone1.getText().length() == 0)
//       {
//           JOptionPane.showMessageDialog(this, "Phone Number Incorrect");
//           validation = false;
//       }
//       if(!emailId.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$") || emailId.getText().length() == 0)
//       {
//           JOptionPane.showMessageDialog(this, "Email Id Incorrect");
//           validation = false;
//       }
//       if(!txtPrsnlEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$") || txtPrsnlEmail.getText().length() == 0)
//       {
//           JOptionPane.showMessageDialog(this, "Personal Email Id Incorrect");
//           validation = false;
//       }
//       if( pwdPass1.getText().length() == 0)
//       {
//           JOptionPane.showMessageDialog(this, "Re-Enter New Password Field is Empty");
//           validation = false;
//       }
//       if( !pwdPass1.getText().equals(pwdPass1.getText()))
//       {
//           JOptionPane.showMessageDialog(this, "Password Fields do not match!");
//           validation = false;
//       }
//       
//     return validation;  
//}
    public void updateAutoPupulate(String emailID) {
        String email = emailID;
        updateEmail.setText(email);

        campusAdminInfo.setEmailID(email);
        campusAdminInfo = campusAdminInfoDirectory.autoPopulateUpdate(email);
        updatePhone.setText(campusAdminInfo.getPhone());
        pwdPass.setText(campusAdminInfo.getPassword());
    }
}
