/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package neu.oncampusams.campusadministration.CampusAdmin;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import neu.oncampusams.databaseConnection.JDBCConnection;
import neu.oncampusams.systemadministration.SystemAdmin.Login;
import neu.oncampusams.systemadministration.SystemAdmin.RegistrationDirectory;
import neu.oncampusams.utilities.EmailInfo;
import neu.oncampusams.utilities.SendEmail;

/**
 *
 * @author Yamini Manral
 */
public final class MailingServicesAdmin extends javax.swing.JFrame {

    String emailID = "dmqwbdm.d@northeastern.edu";
    MailingServicesAdminInfo mailingServicesAdminInfo = new MailingServicesAdminInfo();
    MailingServicesAdminDirectory mailingServicesAdminInfoDirectory = new MailingServicesAdminDirectory();

    /**
     * Creates new form test
     */
    public MailingServicesAdmin() {
        initComponents();
        updateAutoPupulate(emailID);
        mailQueryTable();

    }

    public MailingServicesAdmin(String eid) {
        initComponents();
        emailID = eid; //passing the value of emailid
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        packageType = new javax.swing.JComboBox<>();
        sendBtn = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();
        gmailId = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        bg8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mailQueryTable = new javax.swing.JTable();
        queryId = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();
        status = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        bg7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblEmailId = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        updatePhone = new javax.swing.JTextField();
        updateMailAdmin = new javax.swing.JButton();
        pwdPass1 = new javax.swing.JPasswordField();
        lblNewPass1 = new javax.swing.JLabel();
        updateEmail = new javax.swing.JTextField();
        pwdPass = new javax.swing.JTextField();
        bg6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mailing Services Administrator Portal");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(1400, 700));
        setMinimumSize(new java.awt.Dimension(1400, 700));
        setPreferredSize(new java.awt.Dimension(1400, 700));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTabbedPane1.setMaximumSize(new java.awt.Dimension(1600, 1000));
        jTabbedPane1.setMinimumSize(new java.awt.Dimension(1600, 1000));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1600, 1000));

        jPanel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(255, 204, 153));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Student Notification Sender for Outstanding Package Pickup");
        jPanel8.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 800, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Student Email ID");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, 220, 40));

        packageType.setBackground(new java.awt.Color(204, 204, 204));
        packageType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        packageType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Letter ", "Small (S)", "Medium (M)", "Large (L)", "Extra Large (XL)" }));
        packageType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageTypeActionPerformed(evt);
            }
        });
        jPanel8.add(packageType, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 240, 30));

        sendBtn.setBackground(new java.awt.Color(255, 0, 0));
        sendBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        sendBtn.setForeground(new java.awt.Color(255, 255, 255));
        sendBtn.setText("Send Notification");
        sendBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendBtnActionPerformed(evt);
            }
        });
        jPanel8.add(sendBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 310, -1, 40));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Package type");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 190, 260, 40));

        gmailId.setBackground(new java.awt.Color(204, 204, 204));
        gmailId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        gmailId.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gmailId.setBorder(null);
        gmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gmailIdActionPerformed(evt);
            }
        });
        jPanel8.add(gmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 220, 40));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jPanel8.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 220, 10));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 840, 390));

        bg8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/mail_bg.jpg"))); // NOI18N
        jPanel5.add(bg8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        jTabbedPane1.addTab("Send Notification", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/email (1).png")), jPanel5); // NOI18N

        jPanel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mailQueryTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mailQueryTable.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        mailQueryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Query ID", "Raised By", "Contact", "Status", "Description", "Note"
            }
        ));
        mailQueryTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mailQueryTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(mailQueryTable);

        jPanel6.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 940, 110));

        queryId.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel6.add(queryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 150, 120, 40));

        jLabel11.setBackground(new java.awt.Color(0, 0, 0));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel11.setText("Status");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 320, 110, 40));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel18.setText("Query ID");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 110, 40));

        note.setColumns(20);
        note.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        note.setRows(5);
        jScrollPane1.setViewportView(note);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, 90));

        status.setBackground(new java.awt.Color(204, 204, 204));
        status.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Under review", "Processed" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel6.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, 250, 40));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Note");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 210, 110, 40));

        update.setBackground(new java.awt.Color(255, 0, 0));
        update.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update Query");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel6.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 380, 150, 50));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 80, 960, 450));

        bg7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/query_bg.jpg"))); // NOI18N
        jPanel3.add(bg7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 660));

        jTabbedPane1.addTab("Resolve Query", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/solved.png")), jPanel3); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailId.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmailId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailId.setText("Email Id");
        jPanel4.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 170, 40));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Phone Number");
        jPanel4.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 170, 40));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword.setText("Password");
        jPanel4.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 170, 40));

        updatePhone.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        updatePhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updatePhoneActionPerformed(evt);
            }
        });
        jPanel4.add(updatePhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 110, 290, 40));

        updateMailAdmin.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateMailAdmin.setText("Update");
        updateMailAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateMailAdminActionPerformed(evt);
            }
        });
        jPanel4.add(updateMailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 120, 50));

        pwdPass1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel4.add(pwdPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, 290, 40));

        lblNewPass1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNewPass1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass1.setText("Re-Enter New Password");
        jPanel4.add(lblNewPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 210, 40));

        updateEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        updateEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateEmailActionPerformed(evt);
            }
        });
        jPanel4.add(updateEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 60, 290, 40));

        pwdPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        pwdPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPassActionPerformed(evt);
            }
        });
        jPanel4.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 290, 40));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 570, 360));

        bg6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/profile_bg.jpg"))); // NOI18N
        jPanel2.add(bg6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));

        jTabbedPane1.addTab("Profile", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/updated.png")), jPanel2); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 0, 1080, 700));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Northeastern University");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("On-Campus Accommodation");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Management System");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 270, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/neulogo1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 170, 150));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmail.setText("Email:");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 270, -1));

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 540, 90, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Welcome!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 280, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 700));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

        int queryId1 = Integer.parseInt(queryId.getText());
        String note1 = note.getText();
        String status1 = (String) status.getSelectedItem();
        Connection connection = JDBCConnection.Connect();
        try {
            Statement statement = (Statement) connection.createStatement();
            String sql1 = "UPDATE oncampusamsdb.MailPkQueryTable SET NOTE = '" + note1 + "',status ='" + status1 + "'where queryId = " + queryId1 + "";

            System.out.println("sql update student: " + sql1);
            statement.executeUpdate(sql1);
            JOptionPane.showMessageDialog(this, "Query updated succcessfully");

        } catch (SQLException ex) {
            Logger.getLogger(RegistrationDirectory.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel model = (DefaultTableModel) mailQueryTable.getModel();
        model.setRowCount(0);

        mailQueryTable();
        queryId.setText(" ");
        note.setText(" ");
        status.setSelectedIndex(0);
    }//GEN-LAST:event_updateActionPerformed

    private void packageTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageTypeActionPerformed

    private void sendBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendBtnActionPerformed
        // TODO add your handling code here:
        EmailInfo emailInfo = new EmailInfo();

        emailInfo.setGmailId(gmailId.getText());
        Connection connection = JDBCConnection.Connect();

        try {
            Statement statement = (Statement) connection.createStatement();
            String sql = "SELECT * FROM oncampusamsdb.StudentTable WHERE emailId='" + gmailId.getText() + "'";
            System.out.println("sql update student: " + sql);
            ResultSet resultSet = statement.executeQuery(sql);
            if (resultSet.next()) {

                String ptype = (String) packageType.getSelectedItem();
                emailInfo.setSubjectLine("You have got a " + ptype + ". - @NEUMail");
                emailInfo.setBody("We have recieved a Parcel addressed to you, to get more details check your Student Account Mailig Details. "
                        + "Have a Good Day."
                        + " -Northeastern Mailing Services");

                emailInfo = SendEmail.mail(emailInfo);

                JOptionPane.showMessageDialog(this, emailInfo.getBody());
                
                String sql1= "INSERT INTO `oncampusamsdb`.`MailPkTable`(`studentEmail`,`pkType`)VALUES('" + emailInfo.getGmailId()
                    + "' , '" + ptype + "');";
                  statement.executeUpdate(sql1);
            } else {
                JOptionPane.showMessageDialog(this, "Incorrect EmailId");
                gmailId.setText("");
            }
            
            
        } catch (SQLException ex) {
            Logger.getLogger(RegistrationDirectory.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_sendBtnActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna logout?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void gmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gmailIdActionPerformed

    private void updateMailAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateMailAdminActionPerformed
        // TODO add your handling code here:

        if (!(pwdPass.getText()).equals(pwdPass1.getText())) {
            JOptionPane.showMessageDialog(this, "Passwords doesn't match, please try again!");
            pwdPass.setText("");
            pwdPass1.setText("");
            return;
        }
        MailingServicesAdminInfo mailingServicesAdminInfo = new MailingServicesAdminInfo();
        mailingServicesAdminInfo.setPhone(updatePhone.getText());
        mailingServicesAdminInfo.setEmailID(emailID);
        mailingServicesAdminInfo.setPassword(pwdPass1.getText());
        mailingServicesAdminInfoDirectory.updateAdminDetails(mailingServicesAdminInfo);
        updateAutoPupulate(emailID);
        pwdPass.setText("");
        pwdPass1.setText("");
        updatePhone.setText("");
        JOptionPane.showMessageDialog(this, "Details updated successfully!");


    }//GEN-LAST:event_updateMailAdminActionPerformed

    private void updatePhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updatePhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updatePhoneActionPerformed

    private void updateEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_updateEmailActionPerformed

    private void pwdPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPassActionPerformed

    private void mailQueryTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mailQueryTableMouseClicked
        // TODO add your handling code here:

        int index = mailQueryTable.getSelectedRow();

        DefaultTableModel tblModel = (DefaultTableModel) mailQueryTable.getModel();

        String queryId1 = tblModel.getValueAt(index, 0).toString();
        String status1 = tblModel.getValueAt(index, 3).toString();
        String note1 = tblModel.getValueAt(index, 5).toString();

        queryId.setText(queryId1);
        note.setText(note1);
        if (status1.equals("Under review")) {
            status.setSelectedIndex(0);
        }
        if (status1.equals("Processed")) {
            status.setSelectedIndex(1);
        }
    }//GEN-LAST:event_mailQueryTableMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MailingServicesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MailingServicesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MailingServicesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MailingServicesAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MailingServicesAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg6;
    private javax.swing.JLabel bg7;
    private javax.swing.JLabel bg8;
    private javax.swing.JTextField gmailId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblNewPass1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JButton logout;
    private javax.swing.JTable mailQueryTable;
    private javax.swing.JTextArea note;
    private javax.swing.JComboBox<String> packageType;
    private javax.swing.JTextField pwdPass;
    private javax.swing.JPasswordField pwdPass1;
    private javax.swing.JTextField queryId;
    private javax.swing.JButton sendBtn;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JButton update;
    private javax.swing.JTextField updateEmail;
    private javax.swing.JButton updateMailAdmin;
    private javax.swing.JTextField updatePhone;
    // End of variables declaration//GEN-END:variables

    public void SetEmailID() {
        lblEmail.setText(emailID);
    }

    public void updateAutoPupulate(String emailID) {
        String email = emailID;
        updateEmail.setText(email);

        mailingServicesAdminInfo.setEmailID(email);
        mailingServicesAdminInfo = mailingServicesAdminInfoDirectory.autoPopulateUpdate(email);
        updatePhone.setText(mailingServicesAdminInfo.getPhone());
        pwdPass.setText(mailingServicesAdminInfo.getPassword());
    }

    public void mailQueryTable() {
        String email = emailID;
        mailingServicesAdminInfo.setEmailID(email);

        try ( Connection connection = JDBCConnection.Connect()) {
            Statement statement = (Statement) connection.createStatement();

            String sql = "SELECT * FROM oncampusamsdb.MailPkQueryTable";
            System.out.println(sql);
            ResultSet resultSet = statement.executeQuery(sql);
            while (resultSet.next()) {
                String queryId1 = resultSet.getString(1);
                String raisedBy = resultSet.getString(2);
                String contact = resultSet.getString(3);
                String status1 = resultSet.getString(4);
                String description = resultSet.getString(5);
                String note1 = resultSet.getString(6);
                String tbData[] = {queryId1, raisedBy, contact, status1, description, note1};
                DefaultTableModel tblModel = (DefaultTableModel) mailQueryTable.getModel();
                tblModel.addRow(tbData);

            }
            System.out.println("DB Connection Close!!!");
        } catch (HeadlessException | SQLException exception) {
            System.out.println(exception);
            JOptionPane.showMessageDialog(this, exception);
        }
    }
}
