/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package neu.oncampusams.studentrelation.StudentRelations;

import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import neu.oncampusams.campusadministration.CampusAdmin.*;
import neu.oncampusams.charts.ChartCal;

import neu.oncampusams.databaseConnection.JDBCConnection;

import neu.oncampusams.systemadministration.SystemAdmin.Login;

/**
 *
 * @author Yamini Manral
 */
public class Student extends javax.swing.JFrame {

    String emailID;



    /**
     * Creates new form Warden1
     */
    
    StudentInfoDirectory studentDir = new StudentInfoDirectory();
    public Student() {
        initComponents();
        StudentInfo std = StudentInfoDirectory.getStudentHuskyD("test.s@northeastern.edu");
        lblHuskyTotVal.setText(String.valueOf(std.getHuskyDollars()));
       boolean val =  studentDir.getMealBool("test.s@northeastern.edu");
       if(val == false){
           populateMealPlan("test.s@northeastern.edu");
           
           
       }
        populateHuskyTable("test.s@northeastern.edu");
        populateMailTable("test.s@northeastern.edu");
    }
    public Student(String eid) {
        initComponents();
        emailID = eid; //passing the value of emailid
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelHusky = new javax.swing.JPanel();
        lblHuskyTot = new javax.swing.JLabel();
        lblDollar2 = new javax.swing.JLabel();
        lblHuskyTotVal = new javax.swing.JLabel();
        lblAddDollars = new javax.swing.JLabel();
        lblDollar1 = new javax.swing.JLabel();
        txtAddDollars = new javax.swing.JTextField();
        btnRefresh1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        tblHusky = new javax.swing.JTable();
        panelQuery = new javax.swing.JPanel();
        lblQuery = new javax.swing.JLabel();
        jcbQueryType = new javax.swing.JComboBox<>();
        lblQueryDesc = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtQueryDesc = new javax.swing.JTextArea();
        btnSubmit = new javax.swing.JButton();
        panelRoomChange = new javax.swing.JPanel();
        lblRoomChgHead = new javax.swing.JLabel();
        lblRoomType = new javax.swing.JLabel();
        jcbRoomType = new javax.swing.JComboBox<>();
        lblRoomChg = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArRoomChg = new javax.swing.JTextArea();
        btnSubmitRoomChg = new javax.swing.JButton();
        panelUpdate = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblEmailId = new javax.swing.JLabel();
        lblPrsnlEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblNewPass = new javax.swing.JLabel();
        lblNewPass1 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtPrsnlEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        pwdPass1 = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        lblphoto = new javax.swing.JLabel();
        lblclose = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelVending = new javax.swing.JPanel();
        panelVending1 = new javax.swing.JPanel();
        lblPringless = new javax.swing.JLabel();
        lblCaesar = new javax.swing.JLabel();
        lblCoke = new javax.swing.JLabel();
        lblSprite = new javax.swing.JLabel();
        jcbPringless = new javax.swing.JComboBox<>();
        jcbCaesar = new javax.swing.JComboBox<>();
        jcbCoke = new javax.swing.JComboBox<>();
        jcbSprite = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        lblTotVal = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        lblDollar = new javax.swing.JLabel();
        panelMail = new javax.swing.JPanel();
        lblEmailId2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblMail = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        panelMeal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        mpcal = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        mpDisplay = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jcbMealPlan = new javax.swing.JComboBox<>();
        calculateMP = new javax.swing.JButton();
        mpcal1 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        vegancal = new javax.swing.JLabel();
        calculateMP1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Portal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(1060, 700));
        setPreferredSize(new java.awt.Dimension(1400, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1400, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/neulogo1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Location:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 90, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Northeastern University");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("On-Campus Accommodation");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 270, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Welcome, *Student*");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 190, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Management System");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 270, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 160));

        panelHusky.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHuskyTot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHuskyTot.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHuskyTot.setText("Your remaining husky dollars:");
        panelHusky.add(lblHuskyTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 50));

        lblDollar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDollar2.setText("$");
        panelHusky.add(lblDollar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 20, 50));

        lblHuskyTotVal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHuskyTotVal.setForeground(new java.awt.Color(204, 0, 51));
        panelHusky.add(lblHuskyTotVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 170, 50));

        lblAddDollars.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddDollars.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAddDollars.setText("Add Husky Dollars:");
        panelHusky.add(lblAddDollars, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 320, 50));

        lblDollar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDollar1.setText("$");
        panelHusky.add(lblDollar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 20, 50));
        panelHusky.add(txtAddDollars, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 230, 40));

        btnRefresh1.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setText("Refresh");
        btnRefresh1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });
        panelHusky.add(btnRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 80, 40));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelHusky.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 80, 40));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel33.setText("Husky transactions:");
        panelHusky.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 210, 30));

        tblHusky.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction Id", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane9.setViewportView(tblHusky);

        panelHusky.add(jScrollPane9, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 320, 150));

        jTabbedPane1.addTab("Husky Card", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/card.png")), panelHusky); // NOI18N

        panelQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblQuery.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQuery.setText("What is your query about?");
        panelQuery.add(lblQuery, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 240, 40));

        jcbQueryType.setBackground(new java.awt.Color(204, 204, 204));
        jcbQueryType.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbQueryType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finance related", "Mailing services related", "Housekeeping related" }));
        panelQuery.add(jcbQueryType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 240, 30));

        lblQueryDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblQueryDesc.setText("Write your query:");
        panelQuery.add(lblQueryDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 530, 40));

        txtQueryDesc.setColumns(20);
        txtQueryDesc.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtQueryDesc.setRows(5);
        jScrollPane3.setViewportView(txtQueryDesc);

        panelQuery.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 550, 190));

        btnSubmit.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSubmit.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmit.setText("Submit");
        btnSubmit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        panelQuery.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, 60));

        jTabbedPane1.addTab("Raise a query ", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/ask-for-help.png")), panelQuery); // NOI18N

        panelRoomChange.setMaximumSize(new java.awt.Dimension(590, 470));
        panelRoomChange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRoomChgHead.setText("If you are a new student, uou can apply for a new room, or request for a change if you are already assigned one:");
        panelRoomChange.add(lblRoomChgHead, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 770, 40));

        lblRoomType.setText("Select your desired room type");
        panelRoomChange.add(lblRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 240, 40));

        jcbRoomType.setBackground(new java.awt.Color(204, 204, 204));
        jcbRoomType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1BHK", "2BHK", "Studio", "Shared" }));
        jcbRoomType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbRoomTypeActionPerformed(evt);
            }
        });
        panelRoomChange.add(jcbRoomType, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, 30));

        lblRoomChg.setText("Write more about your room change request:");
        panelRoomChange.add(lblRoomChg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 530, 40));

        txtArRoomChg.setColumns(20);
        txtArRoomChg.setRows(5);
        jScrollPane2.setViewportView(txtArRoomChg);

        panelRoomChange.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 550, 190));

        btnSubmitRoomChg.setBackground(new java.awt.Color(0, 0, 0));
        btnSubmitRoomChg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSubmitRoomChg.setForeground(new java.awt.Color(255, 255, 255));
        btnSubmitRoomChg.setText("Submit");
        btnSubmitRoomChg.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnSubmitRoomChg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitRoomChgActionPerformed(evt);
            }
        });
        panelRoomChange.add(btnSubmitRoomChg, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 80, 40));

        jTabbedPane1.addTab("Apply for a room", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/living-room.png")), panelRoomChange); // NOI18N

        panelUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailId.setText("Email Id");
        jPanel9.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 170, 40));

        lblPrsnlEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrsnlEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrsnlEmail.setText("Personal Email Id");
        jPanel9.add(lblPrsnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 170, 40));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Phone Number");
        jPanel9.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 170, 40));

        lblNewPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNewPass.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass.setText("New Password");
        jPanel9.add(lblNewPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 170, 40));

        lblNewPass1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNewPass1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblNewPass1.setText("Re-Enter New Password");
        jPanel9.add(lblNewPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 210, 40));

        txtEmailId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        jPanel9.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 60, 230, 40));

        txtPrsnlEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrsnlEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrsnlEmailActionPerformed(evt);
            }
        });
        jPanel9.add(txtPrsnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 230, 40));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel9.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 230, 40));

        pwdPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel9.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 230, 40));

        pwdPass1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel9.add(pwdPass1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 230, 40));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel9.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 110, 40));

        panelUpdate.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, 570, 390));

        lblphoto.setText("label 2");
        lblphoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelUpdate.add(lblphoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 160, 90, 100));

        lblclose.setText("label 1");
        lblclose.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        lblclose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcloseMouseClicked(evt);
            }
        });
        panelUpdate.add(lblclose, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 160, 90, 100));
        ImageIcon img = new ImageIcon("C:\\Users\\Yamini Manral\\Downloads\\img2.jpg");
        Image myimg = img.getImage();
        Image newimage = myimg.getScaledInstance(
            90,90,
            Image.SCALE_SMOOTH);

        ImageIcon ic = new ImageIcon(newimage);
        lblclose.setIcon(ic);

        jButton1.setText("one button");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        panelUpdate.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 310, -1, -1));

        jTabbedPane1.addTab("Profile", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/updated.png")), panelUpdate); // NOI18N

        panelVending.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVending1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPringless.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPringless.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPringless.setText("Pringless - $1.50");
        panelVending1.add(lblPringless, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 230, 40));

        lblCaesar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCaesar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCaesar.setText("Caesar Salad - $4.50");
        panelVending1.add(lblCaesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 230, 40));

        lblCoke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCoke.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCoke.setText("Coke - $1.00");
        panelVending1.add(lblCoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 40));

        lblSprite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSprite.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSprite.setText("Sprite - $1.00");
        panelVending1.add(lblSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 230, 40));

        jcbPringless.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbPringless.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbPringless.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPringlessActionPerformed(evt);
            }
        });
        panelVending1.add(jcbPringless, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, 40));

        jcbCaesar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbCaesar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCaesarActionPerformed(evt);
            }
        });
        panelVending1.add(jcbCaesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, 40));

        jcbCoke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbCoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCokeActionPerformed(evt);
            }
        });
        panelVending1.add(jcbCoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 100, 40));

        jcbSprite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbSprite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSpriteActionPerformed(evt);
            }
        });
        panelVending1.add(jcbSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 100, 40));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTotal.setText("Total Cost");
        panelVending1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 140, 30));

        lblTotVal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotVal.setForeground(new java.awt.Color(204, 0, 51));
        panelVending1.add(lblTotVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 270, 220, 30));

        btnBuy.setBackground(new java.awt.Color(0, 0, 0));
        btnBuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy.setText("Buy");
        btnBuy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        panelVending1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 110, 60));

        lblDollar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDollar.setText("$");
        panelVending1.add(lblDollar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 20, 50));

        panelVending.add(panelVending1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTabbedPane1.addTab("Vending Machine", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/vending.png")), panelVending); // NOI18N

        panelMail.setToolTipText("");
        panelMail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailId2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblEmailId2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmailId2.setText("Check your mail here");
        panelMail.add(lblEmailId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 450, 40));

        tblMail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tblMail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student Email", "Package Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblMail);

        panelMail.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 110));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Refresh");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        panelMail.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 90, 50));

        jTabbedPane1.addTab("Mail", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/email (1).png")), panelMail); // NOI18N

        panelMeal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mpcal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mpcal.setForeground(new java.awt.Color(204, 0, 51));
        mpcal.setText("total");
        jPanel2.add(mpcal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 320, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("$");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, 20, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Meal Plan:");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 190, 30));

        mpDisplay.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mpDisplay.setText("meal plan");
        jPanel2.add(mpDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 260, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel30.setText("*changes are final, please choose carefully");
        jPanel2.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 310, 340, 30));

        jcbMealPlan.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jcbMealPlan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Non-veg : 7 meals/week - $70", "Non-veg : 15 meals/week - $130", "Non-veg : UNLIMITED MEALS/week - $200", "Veg : 7 meals/week - $65", "Veg : 15 meals/week - $120", "Veg : UNLIMITED MEALS/week - $180", "Vegan : 7 meals/week - $80", "Vegan : 15 meals/week - $140", "Vegan : UNLIMITED MEALS/week - $210", "I don't want to opt ina meal plan" }));
        jPanel2.add(jcbMealPlan, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 270, 30));

        calculateMP.setBackground(new java.awt.Color(0, 0, 0));
        calculateMP.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateMP.setForeground(new java.awt.Color(255, 255, 255));
        calculateMP.setText("Calculate");
        calculateMP.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculateMP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMPActionPerformed(evt);
            }
        });
        jPanel2.add(calculateMP, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 110, 40));

        mpcal1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        mpcal1.setForeground(new java.awt.Color(204, 0, 51));
        mpcal1.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        mpcal1.setText("Selected meal plan:");
        jPanel2.add(mpcal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 190, 30));

        jLabel31.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel31.setText("Total for a semester:");
        jPanel2.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 210, 30));

        vegancal.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        vegancal.setText("To check calories for each meal type, please click below:");
        jPanel2.add(vegancal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 470, 30));

        calculateMP1.setBackground(new java.awt.Color(0, 0, 0));
        calculateMP1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        calculateMP1.setForeground(new java.awt.Color(255, 255, 255));
        calculateMP1.setText("Check your calories");
        calculateMP1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        calculateMP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateMP1ActionPerformed(evt);
            }
        });
        jPanel2.add(calculateMP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 210, 40));

        panelMeal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 110, 610, 360));

        jTabbedPane1.addTab("Meal Plans", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/canteen .png")), panelMeal); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1300, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna logout?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        StudentInfo std = StudentInfoDirectory.getStudentHuskyD("test.s@northeastern.edu");
        lblHuskyTotVal.setText(String.valueOf(std.getHuskyDollars()));
        txtAddDollars.setText("");
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        boolean numeric = true;

        try {
            Double num = Double.parseDouble(txtAddDollars.getText());
        } catch (NumberFormatException e) {
            numeric = false;
        }
        if(numeric){
            double addDollars = Double.parseDouble(txtAddDollars.getText());
        double remDollars = Double.parseDouble(lblHuskyTotVal.getText());
        double newTotal = addDollars + remDollars;
        String emailId = "test.s@northeastern.edu";

        if (addDollars >= 1.0 && addDollars <= 50.0){
            studentDir.updateHuskyDollars(newTotal, emailId);
            JOptionPane.showMessageDialog(this, "Added Husky Dollars to your card!!!");
            JOptionPane.showMessageDialog(this, "Please press Refresh to display the updated balance");
            txtAddDollars.setText("");
            
            studentDir.addHuskyTransactions(emailId,addDollars);
            populateHuskyTable(emailId);

        }
        else if(addDollars > 50.0)
        {
            JOptionPane.showMessageDialog(this, "You can add only upto 50 dollars");

        }
        else if(addDollars == 0.0)
        {
            JOptionPane.showMessageDialog(this, "You should add atleast 1 dollar");

        }

        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void jcbPringlessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPringlessActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbPringlessActionPerformed

    private void jcbCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCaesarActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbCaesarActionPerformed

    private void jcbCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCokeActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbCokeActionPerformed

    private void jcbSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSpriteActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbSpriteActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:

        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        StudentInfo std = StudentInfoDirectory.getStudentHuskyD("test.s@northeastern.edu");
        double remDollars = std.getHuskyDollars();
        double change = remDollars - total;
        if (change < 0){
            JOptionPane.showMessageDialog(this, "Not Enough Balance! Recharge Husky Card!");
        }
        else{
            String emailId = "test.s@northeastern.edu";
            studentDir.updateHuskyDollars(change, emailId);
            JOptionPane.showMessageDialog(this, "Payment Successful!!!");
            jcbPringless.setSelectedIndex(0);
            jcbCaesar.setSelectedIndex(0);
            jcbCoke.setSelectedIndex(0);
            jcbSprite.setSelectedIndex(0);
            lblTotVal.setText("");
        }

    }//GEN-LAST:event_btnBuyActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:

        String queryType = jcbQueryType.getSelectedItem().toString();
        String description = txtQueryDesc.getText();
        String emailId = "test.s@northeastern.edu";
        String contact = "1234567890";
        if(description.equals("") || description.equals(" ")){
            JOptionPane.showMessageDialog(this, "Description is Empty!");
        }
        else{
            if(queryType.equals("Finance related")){
                studentDir.addFinanceQuery(emailId,description);
                JOptionPane.showMessageDialog(this, "Query Submitted!");
                txtQueryDesc.setText("");
                jcbQueryType.setSelectedIndex(0);
            }
            else if(queryType.equals("Mailing services related")){
                studentDir.addMailQuery(emailId,description,contact);
                JOptionPane.showMessageDialog(this, "Query Submitted!");
                txtQueryDesc.setText("");
                jcbQueryType.setSelectedIndex(0);
            }
            else if(queryType.equals("Housekeeping related")){
                studentDir.addHouseKeepingQuery(emailId,description,contact);
                JOptionPane.showMessageDialog(this, "Query Submitted!");
                txtQueryDesc.setText("");
                jcbQueryType.setSelectedIndex(0);
            }
        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void jcbRoomTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbRoomTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcbRoomTypeActionPerformed

    private void btnSubmitRoomChgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitRoomChgActionPerformed
        // TODO add your handling code here:

        String roomType = jcbRoomType.getSelectedItem().toString();
        String description = txtArRoomChg.getText();
        if(description.equals("") || description.equals(" ")){
            JOptionPane.showMessageDialog(this, "Description is Empty!");
        }
        else{
            String emailId = "test.s@northeastern.edu";
            studentDir.addRoomChangeQuery(emailId,description,roomType);
            JOptionPane.showMessageDialog(this,"Room Change Request Submitted.");
            txtArRoomChg.setText("");
            jcbRoomType.setSelectedIndex(0);
        }

    }//GEN-LAST:event_btnSubmitRoomChgActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtPrsnlEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrsnlEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrsnlEmailActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String emailId = txtEmailId.getText();
        String personalEmailId = txtPrsnlEmail.getText();
        String phone = txtPhone.getText();
        String password = pwdPass.getText();

        boolean validation = FormValidation();

        if(validation){

            StudentInfo student = new StudentInfo();

            student.setEmailId(emailId);
            student.setPersonalEmailId(personalEmailId);
            student.setPhone(phone);
            student.setPassword(password);

            studentDir.updateStudentInfo(student);
            JOptionPane.showMessageDialog(this, "Updated Student Info.");

            populateForm(emailId);

        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void calculateMPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMPActionPerformed
        // TODO add your handling code here:
        
        String mp = jcbMealPlan.getSelectedItem().toString();
        String emailId="test.s@northeastern.edu";
        
        Double mealplan = 0.00;
        if(mp.equals("Veg : 7 meals/week - $65")){
             mealplan = 65.00 * 16;
        }else if(mp.equals("Veg : UNLIMITED MEALS/week - $180")){
            mealplan = 180.00 * 16;
        }else if(mp.equals("Veg : 15 meals/week - $120")){
            mealplan = 120.00 * 16;
        }else if(mp.equals("Non-veg : 7 meals/week - $70")){
            mealplan = 70.00 * 16;
        }else if(mp.equals("Non-veg : 15 meals/week - $130")){
            mealplan = 130.00 * 16;
        }else if(mp.equals("Non-veg : UNLIMITED MEALS/week - $200")){
            mealplan = 200.00 * 16;
        }else if(mp.equals("Vegan : 7 meals/week - $80")){
            mealplan = 80.00 * 16;
        }else if(mp.equals("Vegan : 15 meals/week - $140")){
            mealplan = 140.00 * 16;
        }else if(mp.equals("Vegan : UNLIMITED MEALS/week - $210")){
            mealplan = 210.00 * 16;
        }else if(mp.equals("I don't want to opt in a meal plan")){
            mealplan = 0.00;
        }
        
        mpcal.setText(mealplan.toString());
 
        mpDisplay.setText(jcbMealPlan.getSelectedItem().toString());
        studentDir.addMealPlan(emailId, mp, mealplan);
        calculateMP.setEnabled(false);
        
    }//GEN-LAST:event_calculateMPActionPerformed

    private void calculateMP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateMP1ActionPerformed
        // TODO add your handling code here:

            new ChartCal().setVisible(true);
        
    }//GEN-LAST:event_calculateMP1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void lblcloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcloseMouseClicked
dispose();
            }//GEN-LAST:event_lblcloseMouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnSubmitRoomChg;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton calculateMP;
    private javax.swing.JButton calculateMP1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JComboBox<String> jcbCaesar;
    private javax.swing.JComboBox<String> jcbCoke;
    private javax.swing.JComboBox<String> jcbMealPlan;
    private javax.swing.JComboBox<String> jcbPringless;
    private javax.swing.JComboBox<String> jcbQueryType;
    private javax.swing.JComboBox<String> jcbRoomType;
    private javax.swing.JComboBox<String> jcbSprite;
    private javax.swing.JLabel lblAddDollars;
    private javax.swing.JLabel lblCaesar;
    private javax.swing.JLabel lblCoke;
    private javax.swing.JLabel lblDollar;
    private javax.swing.JLabel lblDollar1;
    private javax.swing.JLabel lblDollar2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblEmailId2;
    private javax.swing.JLabel lblHuskyTot;
    private javax.swing.JLabel lblHuskyTotVal;
    private javax.swing.JLabel lblNewPass;
    private javax.swing.JLabel lblNewPass1;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPringless;
    private javax.swing.JLabel lblPrsnlEmail;
    private javax.swing.JLabel lblQuery;
    private javax.swing.JLabel lblQueryDesc;
    private javax.swing.JLabel lblRoomChg;
    private javax.swing.JLabel lblRoomChgHead;
    private javax.swing.JLabel lblRoomType;
    private javax.swing.JLabel lblSprite;
    private javax.swing.JLabel lblTotVal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblclose;
    private javax.swing.JLabel lblphoto;
    private javax.swing.JLabel mpDisplay;
    private javax.swing.JLabel mpcal;
    private javax.swing.JLabel mpcal1;
    private javax.swing.JPanel panelHusky;
    private javax.swing.JPanel panelMail;
    private javax.swing.JPanel panelMeal;
    private javax.swing.JPanel panelQuery;
    private javax.swing.JPanel panelRoomChange;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelVending;
    private javax.swing.JPanel panelVending1;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JPasswordField pwdPass1;
    private javax.swing.JTable tblHusky;
    private javax.swing.JTable tblMail;
    private javax.swing.JTextField txtAddDollars;
    private javax.swing.JTextArea txtArRoomChg;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrsnlEmail;
    private javax.swing.JTextArea txtQueryDesc;
    private javax.swing.JLabel vegancal;
    // End of variables declaration//GEN-END:variables

private boolean FormValidation(){
    boolean validation = true;
    if(!txtPhone.getText().matches("^[0-9]{10}$") || txtPhone.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Phone Number Incorrect");
           validation = false;
       }
       if(!txtEmailId.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$") || txtEmailId.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Email Id Incorrect");
           validation = false;
       }
       if(!txtPrsnlEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$") || txtPrsnlEmail.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Personal Email Id Incorrect");
           validation = false;
       }
       if( pwdPass1.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Re-Enter New Password Field is Empty");
           validation = false;
       }
       if( !pwdPass1.getText().equals(pwdPass.getText()))
       {
           JOptionPane.showMessageDialog(this, "Password Fields do not match!");
           validation = false;
       }
       
     return validation;  
}

private void populateForm(String emailId){
    StudentInfo student = studentDir.getStudentInfo(emailId);
    txtEmailId.setText(student.getEmailId());
    txtPrsnlEmail.setText(student.getPersonalEmailId());
    txtPhone.setText(student.getPhone());
    pwdPass.setText(student.getPassword());
    
}


public void SetEmailID(){
        lblEmail.setText(emailID);
    } 

public void populateHuskyTable(String stdEmail){
        Connection connection = JDBCConnection.Connect() ;
        try {
            PreparedStatement  pst = connection.prepareStatement("SELECT * FROM HuskyTransactions where studentEmail = ?");
            
            pst.setString(1, stdEmail);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String transactionId = rs.getString("transactionId");
                String amount = rs.getString("rechargeAmount");
                
              
                String tbData[] = {transactionId,amount};
                DefaultTableModel tblModel = (DefaultTableModel)tblHusky.getModel();
                tblModel.addRow(tbData);    
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   private void populateMealPlan(String emailId){
    String mp = studentDir.getMealPlanInfo(emailId);
    Double mealplan = 0.00;
        if(mp.equals("Veg : 7 meals/week - $65")){
             mealplan = 65.00 * 16;
             jcbMealPlan.setSelectedIndex(3);
        }else if(mp.equals("Veg : UNLIMITED MEALS/week - $180")){
            mealplan = 180.00 * 16;
            jcbMealPlan.setSelectedIndex(5);
        }else if(mp.equals("Veg : 15 meals/week - $120")){
            mealplan = 120.00 * 16;
            jcbMealPlan.setSelectedIndex(4);
        }else if(mp.equals("Non-veg : 7 meals/week - $70")){
            mealplan = 70.00 * 16;
            jcbMealPlan.setSelectedIndex(0);
        }else if(mp.equals("Non-veg : 15 meals/week - $130")){
            mealplan = 130.00 * 16;
            jcbMealPlan.setSelectedIndex(1);
        }else if(mp.equals("Non-veg : UNLIMITED MEALS/week - $200")){
            mealplan = 200.00 * 16;
            jcbMealPlan.setSelectedIndex(2);
        }else if(mp.equals("Vegan : 7 meals/week - $80")){
            mealplan = 80.00 * 16;
            jcbMealPlan.setSelectedIndex(6);
        }else if(mp.equals("Vegan : 15 meals/week - $140")){
            mealplan = 140.00 * 16;
            jcbMealPlan.setSelectedIndex(7);
        }else if(mp.equals("Vegan : UNLIMITED MEALS/week - $210")){
            mealplan = 210.00 * 16;
        }else if(mp.equals("I don't want to opt in a meal plan")){
            mealplan = 0.00;
            jcbMealPlan.setSelectedIndex(8);
        }
        
        
        mpcal.setText(mealplan.toString());
 
        mpDisplay.setText(jcbMealPlan.getSelectedItem().toString());
        calculateMP.setEnabled(false);
}

   public void populateMailTable(String stdEmail){
        Connection connection = JDBCConnection.Connect() ;
        try {
            PreparedStatement  pst = connection.prepareStatement("SELECT studentEmail,pkType FROM MailPkTable where studentEmail = ?");
            
            pst.setString(1, stdEmail);
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()){
                String stdEmail1 = rs.getString("studentEmail");
                String pkType = rs.getString("pkType");
                
              
                String tbData[] = {stdEmail1,pkType};
                DefaultTableModel tblModel = (DefaultTableModel)tblMail.getModel();
                tblModel.setRowCount(0);
                tblModel.addRow(tbData);    
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(Student.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   
   
   
   
}
