/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package neu.oncampusams.studentrelation.StudentRelations;

import javax.swing.JOptionPane;
import neu.oncampusams.campusadministration.CampusAdmin.*;

/**
 *
 * @author Yamini Manral
 */
public class Student extends javax.swing.JFrame {

    String emailID;



    /**
     * Creates new form Warden1
     */
    
    StudentInfoDirectory studentDir = new StudentInfoDirectory();
    public Student() {
        initComponents();
        StudentInfo std = StudentInfoDirectory.getStudentHuskyD("test.s@northeastern.edu");
        lblHuskyTotVal.setText(String.valueOf(std.getHuskyDollars()));
        
    }
    public Student(String eid) {
        initComponents();
        emailID = eid; //passing the value of emailid
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelBilling = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jLabel38 = new javax.swing.JLabel();
        panelHusky = new javax.swing.JPanel();
        lblHuskyTot = new javax.swing.JLabel();
        lblDollar2 = new javax.swing.JLabel();
        lblHuskyTotVal = new javax.swing.JLabel();
        lblAddDollars = new javax.swing.JLabel();
        lblDollar1 = new javax.swing.JLabel();
        txtAddDollars = new javax.swing.JTextField();
        btnRefresh1 = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        panelQuery = new javax.swing.JPanel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel34 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        panelRoomChange = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        panelUpdate = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        lblEmailId = new javax.swing.JLabel();
        lblPrsnlEmail = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        txtPrsnlEmail = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        pwdPass = new javax.swing.JPasswordField();
        btnUpdate = new javax.swing.JButton();
        panelVending = new javax.swing.JPanel();
        panelVending1 = new javax.swing.JPanel();
        lblPringless = new javax.swing.JLabel();
        lblCaesar = new javax.swing.JLabel();
        lblCoke = new javax.swing.JLabel();
        lblSprite = new javax.swing.JLabel();
        jcbPringless = new javax.swing.JComboBox<>();
        jcbCaesar = new javax.swing.JComboBox<>();
        jcbCoke = new javax.swing.JComboBox<>();
        jcbSprite = new javax.swing.JComboBox<>();
        lblTotal = new javax.swing.JLabel();
        lblTotVal = new javax.swing.JLabel();
        btnBuy = new javax.swing.JButton();
        lblDollar = new javax.swing.JLabel();
        panelMail = new javax.swing.JPanel();
        lblEmailId2 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        panelMeal = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Student Portal");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        setMaximumSize(new java.awt.Dimension(1060, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1060, 700));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/neulogo1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Location:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Logout");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 90, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Northeastern University");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("On-Campus Accommodation");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 270, -1));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Welcome, *Student*");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, 190, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Management System");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 270, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 160));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        panelBilling.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel19.setText("Monthly rent (static):");
        panelBilling.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 210, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(204, 0, 51));
        jLabel20.setText("*Display monthly rent*");
        panelBilling.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 160, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel21.setText("$");
        panelBilling.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 10, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel22.setText("Husky transactions:");
        panelBilling.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, 210, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "transaction", "amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        panelBilling.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 140, 320, 150));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel23.setText("Total (static):");
        panelBilling.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 310, 140, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 0, 51));
        jLabel24.setText("*Display total of meal plans*");
        panelBilling.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 310, 280, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("$");
        panelBilling.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 10, 30));

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel26.setText("Grand Total:");
        panelBilling.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 150, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(204, 0, 51));
        jLabel27.setText("*Meal plan + rent*");
        panelBilling.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 160, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel28.setText("$");
        panelBilling.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 10, 30));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Month", "Meal Plan"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        panelBilling.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 320, 150));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel38.setText("Meal plan per month:");
        panelBilling.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 210, 30));

        jTabbedPane1.addTab("Billing", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/dollar-symbol.png")), panelBilling); // NOI18N

        panelHusky.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHuskyTot.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHuskyTot.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblHuskyTot.setText("Your remaining husky dollars:");
        panelHusky.add(lblHuskyTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 320, 50));

        lblDollar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDollar2.setText("$");
        panelHusky.add(lblDollar2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 80, 20, 50));

        lblHuskyTotVal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblHuskyTotVal.setForeground(new java.awt.Color(204, 0, 51));
        panelHusky.add(lblHuskyTotVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 80, 170, 50));

        lblAddDollars.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblAddDollars.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblAddDollars.setText("Add Husky Dollars:");
        panelHusky.add(lblAddDollars, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 320, 50));

        lblDollar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDollar1.setText("$");
        panelHusky.add(lblDollar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 180, 20, 50));
        panelHusky.add(txtAddDollars, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 230, -1));

        btnRefresh1.setBackground(new java.awt.Color(0, 0, 0));
        btnRefresh1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnRefresh1.setForeground(new java.awt.Color(255, 255, 255));
        btnRefresh1.setText("Refresh");
        btnRefresh1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnRefresh1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefresh1ActionPerformed(evt);
            }
        });
        panelHusky.add(btnRefresh1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 80, 40));

        btnAdd.setBackground(new java.awt.Color(0, 0, 0));
        btnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        panelHusky.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 80, 40));

        jTabbedPane1.addTab("Husky Card", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/credit-card.png")), panelHusky); // NOI18N

        panelQuery.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jComboBox12.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Finance related", "Mailing services related", " " }));
        panelQuery.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 240, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("What is your query about?");
        panelQuery.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 240, 40));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextArea2.setRows(5);
        jScrollPane3.setViewportView(jTextArea2);

        panelQuery.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 550, 190));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setText("Write your query:");
        panelQuery.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 530, 40));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setText("Submit");
        jButton4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelQuery.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 110, 60));

        jTabbedPane1.addTab("Raise a query ", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/query.png")), panelQuery); // NOI18N

        panelRoomChange.setMaximumSize(new java.awt.Dimension(590, 470));
        panelRoomChange.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("This page is for requesting a room change:");
        panelRoomChange.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 350, 40));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        panelRoomChange.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 550, 190));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Submit");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelRoomChange.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 410, 80, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Write more about your room change request:");
        panelRoomChange.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 530, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setText("Select your desired room type");
        panelRoomChange.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, 240, 40));

        jComboBox11.setBackground(new java.awt.Color(204, 204, 204));
        jComboBox11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1BHK", "2BHK", "Studio", "Shared" }));
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });
        panelRoomChange.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 240, 30));

        jTabbedPane1.addTab("Request a room change", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/query.png")), panelRoomChange); // NOI18N

        panelUpdate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblEmailId.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblEmailId.setText("Email Id");
        jPanel9.add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 170, 40));

        lblPrsnlEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPrsnlEmail.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPrsnlEmail.setText("Personal Email Id");
        jPanel9.add(lblPrsnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 40));

        lblPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPhone.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPhone.setText("Phone Number");
        jPanel9.add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 170, 40));

        lblPassword.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPassword.setText("Password");
        jPanel9.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 170, 40));

        txtEmailId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        jPanel9.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, 230, 40));

        txtPrsnlEmail.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPrsnlEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPrsnlEmailActionPerformed(evt);
            }
        });
        jPanel9.add(txtPrsnlEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 100, 230, 40));

        txtPhone.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneActionPerformed(evt);
            }
        });
        jPanel9.add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 230, 40));

        pwdPass.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jPanel9.add(pwdPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 230, 40));

        btnUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel9.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 110, 40));

        panelUpdate.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 520, 390));

        jTabbedPane1.addTab("Update details", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/refresh-page-option.png")), panelUpdate); // NOI18N

        panelVending.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelVending1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPringless.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblPringless.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblPringless.setText("Pringless - $1.50");
        panelVending1.add(lblPringless, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, 230, 40));

        lblCaesar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCaesar.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCaesar.setText("Caesar Salad - $4.50");
        panelVending1.add(lblCaesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 230, 40));

        lblCoke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCoke.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblCoke.setText("Coke - $1.00");
        panelVending1.add(lblCoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 230, 40));

        lblSprite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblSprite.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblSprite.setText("Sprite - $1.00");
        panelVending1.add(lblSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 230, 40));

        jcbPringless.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbPringless.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbPringless.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbPringlessActionPerformed(evt);
            }
        });
        panelVending1.add(jcbPringless, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, 100, 40));

        jcbCaesar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbCaesar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbCaesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCaesarActionPerformed(evt);
            }
        });
        panelVending1.add(jcbCaesar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 100, 40));

        jcbCoke.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbCoke.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbCoke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbCokeActionPerformed(evt);
            }
        });
        panelVending1.add(jcbCoke, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 100, 40));

        jcbSprite.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jcbSprite.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3" }));
        jcbSprite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbSpriteActionPerformed(evt);
            }
        });
        panelVending1.add(jcbSprite, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 210, 100, 40));

        lblTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotal.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        lblTotal.setText("Total Cost");
        panelVending1.add(lblTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 140, 30));

        lblTotVal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTotVal.setForeground(new java.awt.Color(204, 0, 51));
        panelVending1.add(lblTotVal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 280, 30));

        btnBuy.setBackground(new java.awt.Color(0, 0, 0));
        btnBuy.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnBuy.setForeground(new java.awt.Color(255, 255, 255));
        btnBuy.setText("Buy");
        btnBuy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btnBuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuyActionPerformed(evt);
            }
        });
        panelVending1.add(btnBuy, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 110, 60));

        lblDollar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblDollar.setText("$");
        panelVending1.add(lblDollar, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 20, 50));

        panelVending.add(panelVending1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jTabbedPane1.addTab("Vending Machine", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/vending-machine.png")), panelVending); // NOI18N

        panelMail.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblEmailId2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmailId2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblEmailId2.setText("Check your mail here");
        panelMail.add(lblEmailId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 450, 40));

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Student ID", "Package Type"
            }
        ));
        jScrollPane4.setViewportView(jTable2);

        panelMail.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, -1, 110));

        jButton6.setBackground(new java.awt.Color(0, 0, 0));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Refresh");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        panelMail.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 310, 90, 50));

        jTabbedPane1.addTab("Mail", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/email.png")), panelMail); // NOI18N

        panelMeal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(204, 0, 51));
        jLabel9.setText("*Display total*");
        panelMeal.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 160, 30));

        jComboBox2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Veg", "Non-veg", "Vegan" }));
        panelMeal.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 100, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel15.setText("Choose meal type:");
        panelMeal.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 210, 30));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setText("$");
        panelMeal.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 10, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel17.setText("Total for a week:");
        panelMeal.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 210, 30));

        jTabbedPane1.addTab("Meal Plans", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/food.png")), panelMeal); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1300, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtPrsnlEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPrsnlEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPrsnlEmailActionPerformed

    private void txtPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:

        String emailId = txtEmailId.getText();
        String personalEmailId = txtPrsnlEmail.getText();
        String phone = txtPhone.getText();
        String password = pwdPass.getText();

        boolean validation = FormValidation();

        if(validation){

            StudentInfo student = new StudentInfo();

            student.setEmailId(emailId);
            student.setPersonalEmailId(personalEmailId);
            student.setPhone(phone);
            student.setPassword(password);

            studentDir.updateStudentInfo(student);
            JOptionPane.showMessageDialog(this, "Updated Student Info.");

            populateForm(emailId);

        }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnRefresh1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefresh1ActionPerformed
        // TODO add your handling code here:
        StudentInfo std = StudentInfoDirectory.getStudentHuskyD("test.s@northeastern.edu");
        lblHuskyTotVal.setText(String.valueOf(std.getHuskyDollars()));
        txtAddDollars.setText("");
    }//GEN-LAST:event_btnRefresh1ActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:

        boolean numeric = true;

        try {
            Double num = Double.parseDouble(txtAddDollars.getText());
        } catch (NumberFormatException e) {
            numeric = false;
        }
        if(numeric){
            double addDollars = Double.parseDouble(txtAddDollars.getText());
        double remDollars = Double.parseDouble(lblHuskyTotVal.getText());
        double newTotal = addDollars + remDollars;
        String emailId = "test.s@northeastern.edu";

        if (addDollars >= 1.0 && addDollars <= 50.0){
            studentDir.updateHuskyDollars(newTotal, emailId);
            JOptionPane.showMessageDialog(this, "Added Husky Dollars to your card!!!");
            JOptionPane.showMessageDialog(this, "Please press Refresh to display the updated balance");
            txtAddDollars.setText("");

        }
        else if(addDollars > 50.0)
        {
            JOptionPane.showMessageDialog(this, "You can add only upto 50 dollars");

        }
        else if(addDollars == 0.0)
        {
            JOptionPane.showMessageDialog(this, "You should add atleast 1 dollar");

        }

        }
        
    }//GEN-LAST:event_btnAddActionPerformed

    private void jcbPringlessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbPringlessActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbPringlessActionPerformed

    private void jcbCaesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCaesarActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbCaesarActionPerformed

    private void jcbCokeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbCokeActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbCokeActionPerformed

    private void jcbSpriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbSpriteActionPerformed
        // TODO add your handling code here:
        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        lblTotVal.setText(String.valueOf(total));
    }//GEN-LAST:event_jcbSpriteActionPerformed

    private void btnBuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuyActionPerformed
        // TODO add your handling code here:

        int pringlessNo = Integer.valueOf((String)jcbPringless.getSelectedItem());
        int caesarNo = Integer.valueOf((String)jcbCaesar.getSelectedItem());
        int cokeNo = Integer.valueOf((String)jcbCoke.getSelectedItem());
        int spriteNo = Integer.valueOf((String)jcbSprite.getSelectedItem());

        double total = StudentInfoDirectory.calculateTotalCost(pringlessNo,caesarNo,cokeNo,spriteNo);

        StudentInfo std = StudentInfoDirectory.getStudentHuskyD("test.s@northeastern.edu");
        double remDollars = std.getHuskyDollars();
        double change = remDollars - total;
        if (change < 0){
            JOptionPane.showMessageDialog(this, "Not Enough Balance! Recharge Husky Card!");
        }
        else{
            String emailId = "test.s@northeastern.edu";
            studentDir.updateHuskyDollars(change, emailId);
            JOptionPane.showMessageDialog(this, "Payment Successful!!!");
            jcbPringless.setSelectedIndex(0);
            jcbCaesar.setSelectedIndex(0);
            jcbCoke.setSelectedIndex(0);
            jcbSprite.setSelectedIndex(0);
            lblTotVal.setText("");
        }

    }//GEN-LAST:event_btnBuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Student.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBuy;
    private javax.swing.JButton btnRefresh1;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JComboBox<String> jcbCaesar;
    private javax.swing.JComboBox<String> jcbCoke;
    private javax.swing.JComboBox<String> jcbPringless;
    private javax.swing.JComboBox<String> jcbSprite;
    private javax.swing.JLabel lblAddDollars;
    private javax.swing.JLabel lblCaesar;
    private javax.swing.JLabel lblCoke;
    private javax.swing.JLabel lblDollar;
    private javax.swing.JLabel lblDollar1;
    private javax.swing.JLabel lblDollar2;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblEmailId2;
    private javax.swing.JLabel lblHuskyTot;
    private javax.swing.JLabel lblHuskyTotVal;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPringless;
    private javax.swing.JLabel lblPrsnlEmail;
    private javax.swing.JLabel lblSprite;
    private javax.swing.JLabel lblTotVal;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JPanel panelBilling;
    private javax.swing.JPanel panelHusky;
    private javax.swing.JPanel panelMail;
    private javax.swing.JPanel panelMeal;
    private javax.swing.JPanel panelQuery;
    private javax.swing.JPanel panelRoomChange;
    private javax.swing.JPanel panelUpdate;
    private javax.swing.JPanel panelVending;
    private javax.swing.JPanel panelVending1;
    private javax.swing.JPasswordField pwdPass;
    private javax.swing.JTextField txtAddDollars;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPrsnlEmail;
    // End of variables declaration//GEN-END:variables

private boolean FormValidation(){
    boolean validation = true;
    if(!txtPhone.getText().matches("^[0-9]{10}$") || txtPhone.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Phone Number Incorrect");
           validation = false;
       }
       if(!txtEmailId.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$") || txtEmailId.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Email Id Incorrect");
           validation = false;
       }
       if(!txtPrsnlEmail.getText().matches("^[A-Za-z0-9+_.-]+@(.+)$") || txtPrsnlEmail.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Personal Email Id Incorrect");
           validation = false;
       }
       if( pwdPass.getText().length() == 0)
       {
           JOptionPane.showMessageDialog(this, "Password Field is Empty");
           validation = false;
       }
       
     return validation;  
}

private void populateForm(String emailId){
    StudentInfo student = studentDir.getStudentInfo(emailId);
    txtEmailId.setText(student.getEmailId());
    txtPrsnlEmail.setText(student.getPersonalEmailId());
    txtPhone.setText(student.getPhone());
    pwdPass.setText(student.getPassword());
    
}


public void SetEmailID(){
        lblEmail.setText(emailID);
    } 




}
