/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package neu.oncampusams.studentrelation.StudentRelations;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import neu.oncampusams.databaseConnection.JDBCConnection;
import neu.oncampusams.systemadministration.SystemAdmin.Login;
import neu.oncampusams.systemadministration.SystemAdmin.RegistrationDirectory;

/**
 *
 * @author Yamini Manral
 */
public class Warden extends javax.swing.JFrame {

    WardenDirectory wardenDirectory = new WardenDirectory();

    /**
     * Creates new form Warden1
     */
    public Warden() {
        initComponents();
        studentTable();
        studentQueryTable();
//        queryTable();
    }
    String emailID;
     public Warden(String eid) {
        initComponents();
        emailID = eid; //passing the value of emailid
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        logout = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        resolveTable = new javax.swing.JTable();
        queryId = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        note = new javax.swing.JTextArea();
        status = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        searchField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        query = new javax.swing.JTextArea();
        submit = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        campus = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        building = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        queryTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Warden Portal");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/neulogo1.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 160));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Location:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Email:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        logout.setBackground(new java.awt.Color(255, 0, 0));
        logout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        logout.setForeground(new java.awt.Color(255, 255, 255));
        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jPanel1.add(logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 100, 90, 40));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Northeastern University");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 270, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("On-Campus Accommodation");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 270, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel6.setText("Welcome!");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 270, 30));

        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Welcome, *Warden*");
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 60, 180, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Management System");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 270, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1060, 160));

        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        resolveTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        resolveTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        resolveTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Query ID", "Raised By", "Contact", "Status", "Description", "Note"
            }
        ));
        resolveTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resolveTableMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(resolveTable);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 1070, 110));

        queryId.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel4.add(queryId, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 190, 120, 40));

        jLabel16.setBackground(new java.awt.Color(0, 0, 0));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Status");
        jPanel4.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 90, -1));

        jLabel18.setBackground(new java.awt.Color(0, 0, 0));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setText("Query ID");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 200, 90, -1));

        note.setColumns(20);
        note.setRows(5);
        jScrollPane5.setViewportView(note);

        jPanel4.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, -1, -1));

        status.setBackground(new java.awt.Color(204, 204, 204));
        status.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Query Raised", "In-Progress", "Query Resolved" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });
        jPanel4.add(status, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 380, 250, 40));

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setText("Note");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 90, -1));

        updateBtn.setBackground(new java.awt.Color(255, 0, 0));
        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update Query");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel4.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 470, 140, 50));

        jTabbedPane1.addTab("Resolve Query", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/solved.png")), jPanel4); // NOI18N

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        searchField.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchField.setText("Search");
        searchField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                searchFieldMouseReleased(evt);
            }
        });
        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                searchFieldKeyReleased(evt);
            }
        });
        jPanel3.add(searchField, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 140, 40));

        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Room number", "Room Type ", "Email", "Phone"
            }
        ));
        jScrollPane1.setViewportView(studentTable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, -1, 210));

        jTabbedPane1.addTab("Student Information", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/student.png")), jPanel3); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Select your campus");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 240, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel9.setText("This page let's you raise query on the behalf of a student to higher management.");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 540, 40));

        query.setColumns(20);
        query.setRows(5);
        jScrollPane2.setViewportView(query);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 200, 80));

        submit.setBackground(new java.awt.Color(0, 0, 0));
        submit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        submit.setForeground(new java.awt.Color(255, 255, 255));
        submit.setText("Submit");
        submit.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        jPanel2.add(submit, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 420, 80, 40));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setText("Type in your query:");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 530, 40));

        campus.setBackground(new java.awt.Color(204, 204, 204));
        campus.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        campus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campusActionPerformed(evt);
            }
        });
        jPanel2.add(campus, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 240, 30));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 530, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel14.setText("Select your building");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 240, 40));

        building.setBackground(new java.awt.Color(204, 204, 204));
        building.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        building.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Building 1", "Building 2", "Building 3", "Building 4", "Building 5" }));
        building.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buildingActionPerformed(evt);
            }
        });
        jPanel2.add(building, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 240, 30));

        queryTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Description", "Status", "Comments"
            }
        ));
        jScrollPane3.setViewportView(queryTable);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 500, 190));

        jTabbedPane1.addTab("Raise Query", new javax.swing.ImageIcon(getClass().getResource("/neu/oncampusams/images/ask-for-help.png")), jPanel2); // NOI18N

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 1060, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        // TODO add your handling code here:
        int a = JOptionPane.showConfirmDialog(null, "Do you really wanna logout?", "Select", JOptionPane.YES_NO_OPTION);
        if(a==0){
            dispose();
            new Login().setVisible(true);
        }
    }//GEN-LAST:event_logoutActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void campusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campusActionPerformed

    private void buildingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buildingActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buildingActionPerformed

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String campus1 = (String) campus.getSelectedItem();
        String building1 = (String) building.getSelectedItem();
        String queryBox = query.getText();

        boolean validation = FormValidation();

        if (validation) {
            WardenInfo wardenInfo = new WardenInfo();
            wardenInfo.setBuilding(building1);
            wardenInfo.setCampus(campus1);
            wardenInfo.setDescription(queryBox);
            wardenInfo.setEmailID("wardenxyz@northeasetrn.com");
            wardenInfo.setRoles("Warden");
            wardenInfo.setQueryStatus("Query Raised");
            wardenDirectory.registerWardenQuery(wardenInfo);
            JOptionPane.showMessageDialog(this, "Warden Query sent to Accomodation Admin secccessfully");
            query.setText("");

        }
        queryTable();
    }//GEN-LAST:event_submitActionPerformed

    private void resolveTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resolveTableMouseClicked
        // TODO add your handling code here:
        int index = resolveTable.getSelectedRow();

        DefaultTableModel tblModel = (DefaultTableModel) resolveTable.getModel();

        String queryId1 = tblModel.getValueAt(index, 0).toString();
        String status1 = tblModel.getValueAt(index, 3).toString();
        String note1 = tblModel.getValueAt(index, 5).toString();

        queryId.setText(queryId1);
        note.setText(note1);
        if (status1.equals("Query Raised")) {
            status.setSelectedIndex(0);
        }
        if (status1.equals("In-Progress")) {
            status.setSelectedIndex(1);
        }
        if (status1.equals("Query Resolved")) {
            status.setSelectedIndex(2);
        }
    }//GEN-LAST:event_resolveTableMouseClicked

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int queryId1 = Integer.parseInt(queryId.getText());
        String note1 = note.getText();
        String status1 = (String) status.getSelectedItem();
        Connection connection = JDBCConnection.Connect();
        try {
            Statement statement = (Statement) connection.createStatement();
            String sql = "UPDATE oncampusamsdb.WardenQueryTable SET NOTE = '" + note1 + "',status ='" + status1 + "'where queryId = " + queryId1 + "";

            System.out.println("sql update student: " + sql);
            statement.executeUpdate(sql);

        } catch (SQLException ex) {
            Logger.getLogger(RegistrationDirectory.class.getName()).log(Level.SEVERE, null, ex);
        }

        DefaultTableModel model = (DefaultTableModel) resolveTable.getModel();
        model.setRowCount(0);

        studentQueryTable();
        queryId.setText(" ");
        note.setText(" ");
        status.setSelectedIndex(0);

    }//GEN-LAST:event_updateBtnActionPerformed

    private void searchFieldMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchFieldMouseReleased
        // TODO add your handling code here:


    }//GEN-LAST:event_searchFieldMouseReleased

    private void searchFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyReleased
        // TODO add your handling code here:

        String query1 = searchField.getText();
        filterSearch(query1);
    }//GEN-LAST:event_searchFieldKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Warden.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Warden().setVisible(true);
            }
        });
    }

    private boolean FormValidation() {

        if (query.getText().length() == 0) {
            JOptionPane.showMessageDialog(this, "First Name Empty");
            return false;
        }

        return true;
    }

    private void queryTable() {
        DefaultTableModel model = (DefaultTableModel) queryTable.getModel();
        try {
            try ( Connection connection = JDBCConnection.Connect()) {
                Statement statement = (Statement) connection.createStatement();
                String sql = "Select description, status, note from oncampusamsdb.AccQueryTable";
                ResultSet resultSet = statement.executeQuery(sql);
                WardenInfo wardenInfo = new WardenInfo();
                while (resultSet.next()) {
                    String queryId = resultSet.getString(1);
                    String raisedBy = resultSet.getString(2);
                    String contact = resultSet.getString(3);

                    String tbData[] = {queryId, raisedBy, contact};
                    DefaultTableModel tblModel = (DefaultTableModel) queryTable.getModel();
                    tblModel.addRow(tbData);

                }

            }
            System.out.println("DB Connection Close!!!");
        } catch (HeadlessException | SQLException exception) {
            System.out.println(exception);
            JOptionPane.showMessageDialog(this, exception);
        }
    }

    private void studentTable() {
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        try {
            try ( Connection connection = JDBCConnection.Connect()) {
                Statement statement = (Statement) connection.createStatement();
                String wardenId = "1";
                String sql = "Select fname,lname,roomNo,roomType, emailId, phone from oncampusamsdb.StudentTable WHERE wardenId = '" + wardenId + "'";
                ResultSet resultSet = statement.executeQuery(sql);
                while (resultSet.next()) {
                    String fname = resultSet.getString(1);
                    String lname = resultSet.getString(2);
                    String roomNo = resultSet.getString(3);
                    String roomType = resultSet.getString(4);
                    String emailId = resultSet.getString(5);
                    String phone = resultSet.getString(6);
                    String name = fname + " " + lname;
                    String tbData[] = {name, roomNo, roomType, emailId, phone};
                    DefaultTableModel tblModel = (DefaultTableModel) studentTable.getModel();
                    tblModel.addRow(tbData);

                }

            }
            System.out.println("DB Connection Close!!!");
        } catch (HeadlessException | SQLException exception) {
            System.out.println(exception);
            JOptionPane.showMessageDialog(this, exception);
        }
    }

    private void studentQueryTable() {
        DefaultTableModel model = (DefaultTableModel) resolveTable.getModel();
        try {
            try ( Connection connection = JDBCConnection.Connect()) {
                Statement statement = (Statement) connection.createStatement();
                String wardenEmail = "alpha";
                String sql = "Select queryId,raisedBy,contact,status, description, note from oncampusamsdb.WardenQueryTable WHERE wardenEmail = '" + wardenEmail + "'";
                ResultSet resultSet = statement.executeQuery(sql);
                while (resultSet.next()) {
                    String queryId1 = resultSet.getString(1);
                    String raisedBy = resultSet.getString(2);
                    String contact = resultSet.getString(3);
                    String status1 = resultSet.getString(4);
                    String description = resultSet.getString(5);
                    String note1 = resultSet.getString(6);
                    String tbData[] = {queryId1, raisedBy, contact, status1, description, note1};
                    DefaultTableModel tblModel = (DefaultTableModel) resolveTable.getModel();
                    tblModel.addRow(tbData);

                }

            }
            System.out.println("DB Connection Close!!!");
        } catch (HeadlessException | SQLException exception) {
            System.out.println(exception);
            JOptionPane.showMessageDialog(this, exception);
        }
    }

    private void filterSearch(String query) {
        DefaultTableModel model = (DefaultTableModel) studentTable.getModel();
        TableRowSorter<DefaultTableModel> tableRowSorter = new TableRowSorter<>(model);
        studentTable.setRowSorter(tableRowSorter);
        tableRowSorter.setRowFilter(RowFilter.regexFilter(query));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> building;
    private javax.swing.JComboBox<String> campus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JButton logout;
    private javax.swing.JTextArea note;
    private javax.swing.JTextArea query;
    private javax.swing.JTextField queryId;
    private javax.swing.JTable queryTable;
    private javax.swing.JTable resolveTable;
    private javax.swing.JTextField searchField;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JTable studentTable;
    private javax.swing.JButton submit;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables

 public void SetEmailID(){
        lblEmail.setText(emailID);
    } 
}
 

